variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

lint:
  stage: test
  image: golang:1.14.0
  services:
    - docker:dind
  script:
    - go get -u github.com/googleapis/api-linter/cmd/api-linter
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - api-linter api/cardpack_service.proto api/model.proto api/user_service.proto game/game_service.proto
