variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

lint:
  stage: test
  image: golang:1.13.5
  services:
    - docker:dind
  script:
    - apt-get update
    - apt-get -y install git unzip build-essential autoconf libtool

    - git clone https://github.com/google/protobuf.git
    - cd protobuf
    - ./autogen.sh
    - ./configure
    - make
    - make install
    - ldconfig
    - make clean
    - cd ..
    - rm -r protobuf

    - go get -u github.com/googleapis/api-linter/cmd/api-linter
    - go get -u google.golang.org/grpc
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - api-linter api/cardpack_service.proto api/model.proto api/user_service.proto game/game_service.proto
