variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

lint:
  stage: test
  image: golang:1.14.0
  services:
    - docker:dind
  script:
      # Download required protos.
    - cd /
    - git clone https://github.com/googleapis/api-common-protos.git
      # Return back to original directory.
    - cd /builds/cards-against-humanity/cards-proto
    - go get -u github.com/googleapis/api-linter/cmd/api-linter
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - api-linter --proto-path=/api-common-protos api/cardpack_service.proto api/game_service.proto api/model.proto api/user_service.proto
