name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    container: golang:latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          go get -u github.com/googleapis/api-linter/cmd/api-linter
          go get -u github.com/golang/protobuf/protoc-gen-go
          api-linter --proto-path=/api-common-protos crusty_cards_api/cardpack_service.proto crusty_cards_api/game_service.proto crusty_cards_api/model.proto crusty_cards_api/user_service.proto
